# Generated by Django 6.1.1 on 2026-09-11 15:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('hex_code', models.CharField(default='#000000', help_text='e.g. #7A0F1F', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(max_length=80, verbose_name='city / area')),
                ('address', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='$', max_length=5)),
                ('payment_method', models.CharField(default='Cash on delivery', editable=False, max_length=40)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('shipped', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('email_sent', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='$', max_length=5)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=8)),
                ('free_delivery_over', models.DecimalField(blank=True, decimal_places=2, default=Decimal('75.00'), help_text='Orders with a subtotal at or above this amount ship free. Leave empty to disable.', max_digits=8, null=True)),
                ('delivery_time', models.CharField(default='2–4 business days', max_length=100)),
                ('announcement', models.CharField(blank=True, default='Cash on delivery on every order', help_text='Short message shown in the bar at the top of every page.', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, help_text='International format, digits only, e.g. 96170123456', max_length=20)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Optional. Upload the logo file to replace the text logo in the header.', upload_to='branding/')),
                ('hero_title', models.CharField(default='Everyday elegance, made casual.', max_length=120)),
                ('hero_subtitle', models.CharField(blank=True, default='Soft basics, easy sets and sportswear for her and him — delivered to your door, paid on arrival.', max_length=240)),
                ('hero_image', models.ImageField(blank=True, upload_to='branding/')),
            ],
            options={
                'verbose_name': 'store settings',
                'verbose_name_plural': 'store settings',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('path', models.CharField(editable=False, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Optional. If empty, the first product image in this category is used.', upload_to='categories/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('sku', models.CharField(blank=True, max_length=40, verbose_name='SKU')),
                ('description', models.TextField(blank=True)),
                ('details', models.TextField(blank=True, help_text='One item per line, shown as a list.', verbose_name='fabric & care')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Set higher than the price to show the item as on sale.', max_digits=10, null=True, verbose_name='original price')),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='visible on site')),
                ('is_featured', models.BooleanField(default=False, verbose_name='best seller')),
                ('is_sample', models.BooleanField(default=False, editable=False, help_text='Created by load_sample_data; removed by remove_sample_data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='products', to='store.category')),
                ('colors', models.ManyToManyField(blank=True, related_name='products', to='store.color')),
                ('sizes', models.ManyToManyField(blank=True, related_name='products', to='store.size')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt', models.CharField(blank=True, max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, help_text='Optional. Selecting this color on the product page shows this image.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
