# Generated by Django 6.1.1 on 2026-09-14 11:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='What customers type at checkout, e.g. WELCOME10. Not case-sensitive.', max_length=30, unique=True)),
                ('kind', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off'), ('free_delivery', 'Free delivery')], default='percent', max_length=20, verbose_name='discount type')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='10 means 10% off (percentage) or 10 off in your currency (fixed amount). Ignored for free delivery.', max_digits=8)),
                ('min_subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. The bag subtotal needed before the code can be used.', max_digits=10, null=True, verbose_name='minimum order')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='valid until')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Optional. Total number of orders that can use this code.', null=True, verbose_name='usage limit')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
