# Generated by Django 6.1.1 on 2026-09-14 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('online', 'Online'), ('in_store', 'In store')], default='online', help_text='Online orders come from the website; in-store sales are recorded in the store manager.', max_length=10, verbose_name='sold'),
        ),
        migrations.AddField(
            model_name='order',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='The admin who recorded an in-store sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
